[package]
name = "easexx"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
dotenvy = "0.15"
env_logger = "0.11"
anyhow = "1.0"

[dev-dependencies]
rstest = "0.25.0"